---
# Encapsulating the reboot-and-wait-for logic in a task list,
# so that notifying a single handler (i.e. "reboot") will run
# multiple tasks. Declaring this handler at the site level so
# it's available regardless of role or playbook.
- name: reboot
  include: reboot.yml
