#!/usr/bin/env ansible-playbook
---
  # Staging machines should be provisioned with local code,
  # rather than pulling down stable releases from the app code.
  # Therefore build the local debs before provisioning the staging hosts.
- include: build-deb-pkgs.yml
  tags: build_debs

- name: Add FPF apt repository and install base packages.
  hosts: staging
  pre_tasks:
    - name: Extract ec2 vars when in AWS
      ec2_facts:
      when: amazon_builder

    - name: Set remote host for any reboot tasks under AWS
      set_fact:
        remote_host_ref: "{{ ansible_ec2_public_hostname }}"
      when: amazon_builder
  roles:
    - { role: common, tags: common }
    - { role: tor-hidden-services, tags: tor }
    - { role: install-fpf-repo, tags: [fpfrepo] }
    - { role: grsecurity, when: grsecurity, tags: [grsec, grsecurity] }
    - { role: install-local-packages, tags: [install_local_packages, rebuild],
        when: install_local_packages }
  sudo: yes

- name: Configure OSSEC manager.
  hosts: mon-staging
  roles:
    - { role: ossec-server, tags: [ ossec, ossec_server ] }
  sudo: yes

- name: Configure SecureDrop Application Server.
  hosts: app-staging
  roles:
    - { role: ossec-agent, tags: [ ossec, ossec_agent ] }
    - { role: app, tags: app }
    - { role: app-test, tags: app-test }
  sudo: yes

  # Set iptables rules with exemptions for staging that permit direct access for SSH.
  # The overrides that permit direct access are managed in group_vars/staging.yml,
  # and default false in production environments, in order to force SSH traffic over Tor.
- name: Configure host firewalls (with direct access for staging).
  hosts: staging
  roles:
    - { role: restrict-direct-access, tags: [ common, restrict-direct-access ] }
  sudo: yes
