---
# Reuse validation logic.
- include: "{{ role_path }}/../validate/tasks/validate_tails_environment.yml"

- include: cleanup_legacy_artifacts.yml

- include: migrate_existing_config.yml

- include: copy_dotfiles.yml

- include: configure_torrc_additions.yml

- include: create_desktop_shortcuts.yml

- include: configure_network_hook.yml

- include: create_ssh_aliases.yml
  # Only Admin Workstation will have ATHS values for SSH, in addition
  # to ATHS value for the Journalist Interface.
  when: find_aths_info_result.matched > 1
