---
# Between 0.3.12 and 0.4, the "Document Interface" was renamed to
# "Journalist Interface". Since multiple scripts expect to readfrom this file,
# we'll rename the old file to handle the transition gracefully.
- name: Migrate Document Interface ATHS file (upgrade only).
  command: >-
    mv --no-clobber
    "{{ tails_config_ansible_base }}/app-document-aths"
    "{{ tails_config_ansible_base }}/app-journalist-aths"
  args:
    # Only run this command if the deprecated file is present.
    removes: "{{ tails_config_ansible_base }}/app-document-aths"

# Between 0.3.12 and 0.4, the `prod-specific.yml` vars file was deprecated
# in favor of `group_vars/all/site-specific`. The latter is not version
# controlled, and so will not exist by default.
- name: Migrate site-specific configuration to new location.
  command: >-
    cp
    "{{ tails_config_ansible_base }}/prod-specific.yml"
    "{{ tails_config_ansible_base }}/group_vars/all/site-specific"
  register: site_specific_vars_migration_result
  args:
    # Only run this command if no site-specific vars exist. First-time
    # installs will create the vars via `./securedrop-admin sdconfig`.
    creates: "{{ tails_config_ansible_base }}/group_vars/all/site-specific"

# If the site-specific vars file was migrated in the previous task, we must
# explicitly include it, since it wasn't present in group_vars/all/ at the
# start of the play, so none of its variables will be defined.
- name: Import newly migrated sites-specific configuration.
  include_vars: "{{ tails_config_ansible_base }}/group_vars/all/site-specific"
  when: site_specific_vars_migration_result|changed
