---
  # Do NOT!!! reload the production iptables rules during the first
  # installation. They will break the ssh connection and because of
  # that it will break the installation leaving you with no remote
  # access to the server. If this happens will need console access
  # to recover access.
  #
  # The staging exemptions will reload the iptables rules after the exemptions
  # are put in place
  #
  # For production systems the iptables rules will not be loaded until the
  # server is rebooted. This also means that any updates to the firewall in the
  # future will require a restart.
  #
  # The process should be re-designed so the iptables rules are not applied in
  # bulk. When that is done this issue will be avoided.

- name: Copy load_iptables if-up script.
  copy:
    src: load_iptables
    dest: /etc/network/if-up.d/load_iptables
    owner: root
    mode: "0744"
  tags:
    - iptables
    - permissions

- name: Create iptables directory.
  file:
    state: directory
    mode: "0700"
    owner: root
    group: root
    dest: /etc/network/iptables
  tags:
    - iptables
    - permissions

- name: Copy IPv4 iptables rules.
  template:
    src: rules_v4
    dest: /etc/network/iptables/rules_v4
    owner: root
    mode: "0644"
  tags:
    - iptables
    - permissions

- name: Copy IPv6 iptables rules.
  copy:
    src: iptables_rules_v6
    dest: /etc/network/iptables/rules_v6
    owner: root
    mode: "0644"
  tags:
    - iptables
    - permissions
