---
- name: Confirm host OS is Tails.
  assert:
    that:
      - ansible_lsb.id == "Tails"
      - ansible_lsb.major_release >= 9
    msg: >-
      SecureDrop requires Tails 3 or greater for workstation environments.

- name: Check for persistence volume.
  stat:
    path: /live/persistence/TailsData_unlocked/persistence.conf
  register: tails_persistence_check_result
  with_items:
    - /live/persistence/TailsData_unlocked/persistence.conf
    - /live/persistence/TailsData_unlocked/openssh-client
    - /home/amnesia/Persistent/securedrop

- name: Confirm persistence volume is configured.
  assert:
    that:
      - item.stat.exists
    msg: >-
      Persistence must configured on the Tails device for the Admin
      Workstation, and the SSH option for persistent dotfiles must be enabled.
      The SecureDrop git repository should be cloned
      to `~/Persistent/securedrop`.
  with_items: "{{ tails_persistence_check_result.results }}"
